<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateTaskRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true; // Authorization handled by middleware
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'description' => ['nullable', 'string'],
            'type' => ['required', 'string', 'max:100', 'in:UI,NUI,UNI,NUNI'],
            'status' => ['nullable', 'boolean'],
            'url' => ['nullable', 'string', 'max:255'],
            'redirect' => ['nullable', 'boolean'],
            'department' => ['nullable', 'string'],
            'category_id' => ['nullable', 'integer', 'exists:categories,id'],
            'task_name' => ['nullable', 'string', 'max:255'],
            'period_type' => ['nullable', 'string', 'max:255'],
            'period_start' => ['nullable', 'date_format:Y-m-d H:i:s'],
            'period_end' => ['nullable', 'date_format:Y-m-d H:i:s', 'after_or_equal:period_start'],
            'time_cloture' => ['nullable', 'date_format:H:i:s'], // Time format: HH:mm:ss
            'time_out' => ['nullable', 'date_format:H:i:s'], // Time format: HH:mm:ss
            'period_days' => ['nullable', 'string'],
            'period_urgent' => ['nullable', 'string'],
            'type_justif' => ['nullable', 'string'],
            'users' => ['nullable', 'string', 'max:255'],
            'step' => ['nullable', 'string', 'max:255', 'in:pending,in_progress,completed'],
            'file' => ['nullable', 'string', 'max:255'], // File ID from files table
            'controller' => ['nullable', 'string', 'max:255'], // Controller user ID or name
            'alarm' => ['nullable', 'string'], // Alarm times as JSON string
            // Rest time is always generated by the app; avoid strict format errors for users
            'rest_time' => ['nullable', 'string', 'max:8'], // e.g. "12:30:00"
            'rest_max' => ['nullable', 'integer', 'min:0'], // Maximum rest count
            // justif_file is not included - always set to null when creating
        ];
    }

    /**
     * Custom attribute names for validation errors.
     * This is what the user will see in error messages instead of the raw field name.
     */
    public function attributes(): array
    {
        return [
            'rest_time' => 'time between alarms',
            'rest_max' => 'maximum alarm repeats',
            'time_cloture' => 'task end time',
            'time_out' => 'task start time',
        ];
    }

    // No extra cross-field validation: alarm start time is optional,
    // and task end time is validated only by the basic rules above.
}
