<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateTaskRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true; // Authorization handled by middleware
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'description' => ['nullable', 'string'],
            'type' => ['required', 'string', 'max:100', 'in:UI,NUI,UNI,NUNI'],
            'status' => ['nullable', 'boolean'],
            'url' => ['nullable', 'string', 'max:255'],
            'redirect' => ['nullable', 'boolean'],
            'department' => ['nullable', 'string'],
            'category_id' => ['nullable', 'integer', 'exists:categories,id'],
            'task_name' => ['nullable', 'string', 'max:255'],
            'period_type' => ['nullable', 'string', 'max:255'],
            'period_start' => ['nullable', 'date_format:Y-m-d H:i:s'],
            'period_end' => ['nullable', 'date_format:Y-m-d H:i:s', 'after_or_equal:period_start'],
            'time_cloture' => ['nullable', 'date_format:H:i:s'], // Time format: HH:mm:ss
            'time_out' => ['nullable', 'date_format:H:i:s'], // Time format: HH:mm:ss
            'period_days' => ['nullable', 'string'],
            'period_urgent' => ['nullable', 'string'],
            'type_justif' => ['nullable', 'string'],
            'users' => ['nullable', 'string', 'max:255'],
            'step' => ['nullable', 'string', 'max:255', 'in:pending,in_progress,completed'],
            'file' => ['nullable', 'string', 'max:255'], // File ID from files table
            'controller' => ['nullable', 'string', 'max:255'], // Controller user ID or name
            'alarm' => ['nullable', 'string'], // Alarm times as JSON string
            // Rest time is always generated by the app; avoid strict format errors for users
            'rest_time' => ['nullable', 'string', 'max:8'], // e.g. "12:30:00"
            'rest_max' => ['nullable', 'integer', 'min:0'], // Maximum rest count
            // justif_file is not included - always set to null when creating
        ];
    }

    /**
     * Custom attribute names for validation errors.
     * This is what the user will see in error messages instead of the raw field name.
     */
    public function attributes(): array
    {
        return [
            'rest_time' => 'time between alarms',
            'rest_max' => 'maximum alarm repeats',
            'time_cloture' => 'task end time',
            'time_out' => 'task start time',
        ];
    }

    /**
     * Configure the validator instance.
     */
    public function withValidator($validator)
    {
        $validator->after(function ($validator) {
            $timeCloture = $this->input('time_cloture');
            $timeOut = $this->input('time_out');

            // Validate that if task end time is set, task start time should also be set
            if ($timeCloture && !$timeOut) {
                $validator->errors()->add(
                    'time_out',
                    'The task start time is required when the task end time is set.'
                );
            }

            // Validate that if task start time is set, task end time should also be set
            if ($timeOut && !$timeCloture) {
                $validator->errors()->add(
                    'time_cloture',
                    'The task end time is required when the task start time is set.'
                );
            }

            // Validate time format if both are set
            if ($timeCloture && $timeOut) {
                try {
                    // Parse time strings (format: HH:mm:ss)
                    $timeClotureParts = explode(':', $timeCloture);
                    $timeOutParts = explode(':', $timeOut);
                    
                    if (count($timeClotureParts) < 2 || count($timeOutParts) < 2) {
                        $validator->errors()->add(
                            'time_cloture',
                            'Invalid time format for task end time. It must be in HH:mm:ss format.'
                        );
                    } else {
                        $timeClotureHour = (int)$timeClotureParts[0];
                        $timeOutHour = (int)$timeOutParts[0];
                        
                        // End time should be after start time on the same day
                        if ($timeClotureHour <= $timeOutHour) {
                            // Check minutes if hours are equal
                            if ($timeClotureHour == $timeOutHour) {
                                $timeClotureMin = (int)$timeClotureParts[1];
                                $timeOutMin = (int)$timeOutParts[1];
                                if ($timeClotureMin <= $timeOutMin) {
                                    $validator->errors()->add(
                                        'time_cloture',
                                        'The task end time must be after the task start time.'
                                    );
                                }
                            } else {
                                $validator->errors()->add(
                                    'time_cloture',
                                    'The task end time must be after the task start time.'
                                );
                            }
                        }
                    }
                } catch (\Exception $e) {
                    $validator->errors()->add(
                        'time_cloture',
                        'Invalid time format for task end time. It must be in HH:mm:ss format.'
                    );
                }
            }
        });
    }
}
